apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: bits-analytics-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4003  # Change this to match your app's port
