apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service  # Ensure this matches the app name in your deployment
  ports:
    - protocol: TCP
      port: 80        # Exposed on the external IP
      targetPort: 4003  # Internal port inside the pod
  type: NodePort       # Expose the service externally via NodePort
